Models/AlterarSenha.cs
using System.ComponentModel.DataAnnotations;

namespace AgendaOnline.Models
{
    public class AlterarSenha
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite a senha atual")]
        public string SenhaAtual { get; set; }
        [Required(ErrorMessage = "Digite a nova senha")]
        public string NovaSenha { get; set; }
        [Required(ErrorMessage = "Confirme a nova senha")]
        [Compare("NovaSenha", ErrorMessage = "Senha não é igual a nova senha")]
        public string ConfirmarNovaSenha { get; set; }
    }
}

Controllers/AlterarSenhaController.cs
using AgendaOnline.Helper.Interface;
using AgendaOnline.Models;
using AgendaOnline.Repositorio.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AgendaOnline.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;

        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenha alterarSenha)
        {
            try
            {
                Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                alterarSenha.Id = usuarioLogado.Id;
                
                if (ModelState.IsValid)
                {
                    _usuarioRepositorio.AlterarSenha(alterarSenha);
                    TempData["MsgSucesso"] = "Senha alterada com sucesso";
                    return View("Index", alterarSenha);
                }

                return View("Index", alterarSenha);
            }
            catch (Exception e)
            {
                TempData["MsgErro"] = $"Algo deu errado! Não foi possivel alterar sua senha, erro: {e.Message}";
                return View("Index", alterarSenha);
            }
        }
    }
}

Views/AlterarSenha/Index.cshtml
@model AlterarSenha

@{
    ViewData["Title"] = "Alterar senha do usuario";
}

<div class="text-center">
    <h1 class="display-4">Alterar senha do usuário</h1>
</div>

@if (TempData["MsgSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
        @TempData["MsgSucesso"]
    </div>
}

@if (TempData["MsgErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
        @TempData["MsgErro"]
    </div>
}

<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">


    <div class="form-group">
        <label for="senha" class="form-label">Senha atual</label>
        <input type="password" asp-for="SenhaAtual" class="form-control" placeholder="Digite a senha atual do usuário">
        @Html.ValidationMessageFor(x=>x.SenhaAtual)
    </div>
    <br />

    <div class="form-group">
        <label for="novaSenha" class="form-label">Nova senha</label>
        <input type="password" asp-for="NovaSenha" class="form-control" placeholder="Digite a nova senha do usuário">
        @Html.ValidationMessageFor(x=>x.NovaSenha)
    </div>
    <br />

    <div class="form-group">
        <label for="confirmarSenha" class="form-label">Confirmar nova senha</label>
        <input type="password" asp-for="ConfirmarNovaSenha" class="form-control" placeholder="Digite a confirmacao da nova senha do usuário">
        @Html.ValidationMessageFor(x=>x.ConfirmarNovaSenha)
    </div>
    <br />

    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Home" asp-action="Index" role="button">Voltar</a>
</form>