Models/Usuario.cs
using AgendaOnline.Data.Enums;
using AgendaOnline.Helper;
using System.ComponentModel.DataAnnotations;

namespace AgendaOnline.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome do usuário")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Digite o login do usuário")]
        public string Login { get; set; }
        [Required(ErrorMessage = "Digite o e-mail do usuário")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é valido")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Digite o senha do usuário")]
        public string Senha { get; set; }
        public DateTime DataCadastro { get; set; }
        public DateTime? DataAlteracao { get; set; }
        [Required(ErrorMessage = "Informe o perfil do usuario")]
        public PerfilEnum? Perfil { get; set; }
        
        public virtual List<Contato> Contatos { get; set; }

        public bool SenhaValidado(string senha)
        {
            return Senha == senha.GerarHash();
        }

        public void SetSenhaHash()
        {
            Senha = Senha.GerarHash();
        }

        public void SetNovaSenha(string novaSenha)
        {
            Senha = novaSenha.GerarHash();
        }

        public string GerarNovaSenha()
        {
            string novaSenha = Guid.NewGuid().ToString().Substring(0,8);
            Senha = novaSenha.GerarHash();
            return novaSenha;
        }
    }
}

Controllers/ContatoController.cs
using AgendaOnline.Filters;
using AgendaOnline.Helper.Interface;
using AgendaOnline.Models;
using AgendaOnline.Repositorio.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AgendaOnline.Controllers
{
    [PagUsuarioLogado]
    public class ContatoController : Controller
    {
        #region - Contrutor
        private readonly IContatoRepositorio _contatoRepositorio;
        private readonly ISessao _sessao;

        public ContatoController(IContatoRepositorio contatoRepositorio, ISessao sessao)
        {
            _contatoRepositorio = contatoRepositorio;
            _sessao = sessao;
        }
        #endregion

        #region - GET
        public IActionResult Index()
        {
            Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();
            var contatos = _contatoRepositorio.BuscarTodos(usuarioLogado.Id);
            return View(contatos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagou = _contatoRepositorio.Apagar(id);
                if (apagou)
                {
                    TempData["MsgSucesso"] = "Contato deletado com sucesso";
                }
                else
                {
                    TempData["MsgErro"] = "Não foi possivel deletar o contato";
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["MsgErro"] = $"Algo deu errado! Não foi possivel deletar o contato, erro: {e.Message}";
                return RedirectToAction("Index"); ;
            }
        }
        #endregion

        #region - POST
        [HttpPost]
        public IActionResult Criar(Contato contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    contato.UsuarioId = usuarioLogado.Id;

                    contato = _contatoRepositorio.Adicionar(contato);
                    TempData["MsgSucesso"] = "Contato cadastrado com sucesso";
                    return RedirectToAction("Index");
                }
                return View(contato);
            }
            catch (Exception e)
            {
                TempData["MsgErro"] = $"Algo deu errado! Não foi possivel cadastrar o contato, erro: {e.Message}";
                return RedirectToAction("Index");
            }
        }
        
        [HttpPost]
        public IActionResult Alterar(Contato contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    contato.UsuarioId = usuarioLogado.Id;

                    contato = _contatoRepositorio.Atualizar(contato);
                    TempData["MsgSucesso"] = "Contato atualizado com sucesso";
                    return RedirectToAction("Index");
                }
                return View("Editar", contato);
            }
            catch (Exception e)
            {
                TempData["MsgErro"] = $"Algo deu errado! Não foi possivel atualizar o contato, erro: {e.Message}";
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region - PUT
        public IActionResult Editar(int id)
        {
            Contato c = _contatoRepositorio.BuscarId(id);
            return View(c);
        }
        #endregion

        #region - Delete
        public IActionResult DeletarConfirmacao(int id)
        {
            Contato c = _contatoRepositorio.BuscarId(id);
            return View(c);
        }
        #endregion
    }
}

Controllers/UsuarioController.cs
using AgendaOnline.Filters;
using AgendaOnline.Models;
using AgendaOnline.Repositorio.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AgendaOnline.Controllers
{
    [PagParaAdmin]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly IContatoRepositorio _contatoRepositorio;

        public UsuarioController(IUsuarioRepositorio usuarioRepositorio, IContatoRepositorio contatoRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _contatoRepositorio = contatoRepositorio;
        }

        #region - Rotas
        public IActionResult Index()
        {
            List<Usuario> usuarios = _usuarioRepositorio.BuscarTodos();
            return View(usuarios);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            Usuario u = _usuarioRepositorio.BuscarId(id);
            return View(u);
        }

        public IActionResult DeletarConfirmacao(int id)
        {
            Usuario u = _usuarioRepositorio.BuscarId(id);
            return View(u);
        }

        public IActionResult ListarContatosPorUsuarioId(int id)
        {
            List<Contato> contatos = _contatoRepositorio.BuscarTodos(id);
            return PartialView("_ContatosUsuario", contatos);
        }

        #endregion

        #region - POST
        [HttpPost]
        public IActionResult Criar(Usuario u)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    u = _usuarioRepositorio.Adicionar(u);
                    TempData["MsgSucesso"] = "Usuario cadastrado com sucesso";
                    return RedirectToAction("Index");
                }
                return View(u);
            }
            catch (Exception e)
            {
                TempData["MsgErro"] = $"Algo deu errado! Não foi possivel cadastrar o usuario, erro: {e.Message}";
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region - PUT
        [HttpPost]
        public IActionResult Editar(UsuarioSemSenha usuarioSemSenha)
        {
            try
            {
                Usuario usuario = null;
                
                if (ModelState.IsValid)
                {
                    usuario = new Usuario()
                    {
                        Id = usuarioSemSenha.Id,
                        Nome = usuarioSemSenha.Nome,
                        Login = usuarioSemSenha.Login,
                        Email = usuarioSemSenha.Email,
                        Perfil = usuarioSemSenha.Perfil
                    };

                    usuario = _usuarioRepositorio.Atualizar(usuario);
                    TempData["MsgSucesso"] = "Usuario atualizado com sucesso";
                    return RedirectToAction("Index");
                }
                return View(usuario);
            }
            catch (Exception e)
            {
                TempData["MsgErro"] = $"Algo deu errado! Não foi possivel atualizar o usuario, erro: {e.Message}";
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region - DELETE
        [HttpGet]
        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagou = _usuarioRepositorio.Apagar(id);
                if (apagou)
                {
                    TempData["MsgSucesso"] = "Usuario deletado com sucesso";
                }
                else
                {
                    TempData["MsgErro"] = "Não foi possivel deletar o usuario";
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["MsgErro"] = $"Algo deu errado! Não foi possivel deletar o usuario, erro: {e.Message}";
                return RedirectToAction("Index"); ;
            }
        }
        #endregion
    }
}

Views/Usuario/Criar.cshtml
@using AgendaOnline.Data.Enums;
@model Usuario

@{
    ViewData["Title"] = "Criar Usuario";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar usuário</h1>
</div>

<form asp-controller="Usuario" asp-action="Criar" method="post">
    
    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Nome do usuário">
        @Html.ValidationMessageFor(x=>x.Nome)
    </div>
    <br />

    <div class="form-group">
        <label for="email" class="form-label">E-mail</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="E-mail do usuário">
        @Html.ValidationMessageFor(x=>x.Email)
    </div>
    <br />

    <div class="form-group">
        <label for="telefone" class="form-label">Login</label>
        <input type="text" asp-for="Login" class="form-control" placeholder="Login do usuário">
        @Html.ValidationMessageFor(x=>x.Login)
    </div>
    <br />
    
    <div class="form-group">
        <label for="telefone" class="form-label">Senha</label>
        <input type="password" asp-for="Senha" class="form-control" placeholder="Senha do usuário">
        @Html.ValidationMessageFor(x=>x.Senha)
    </div>
    <br />

    <div class="form-group">
        <label for="telefone" class="form-label">Perfil</label>
        <select asp-for="Perfil" class="form-control">
            <option value="0">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.Padrao">Padrao</option>
        </select>
    </div>
    <br />

    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

Views/Usuario/DeletarConfirmacao.cshtml
@model Usuario
@{
    ViewData["Title"] = "Confirmação apagar o usuario";
}

<div class="text-center">
    <h3>Realmente deseja apagar o usuario (@Model.Nome)?</h3>
    <br />

    <a class="btn btn-primary" role="button" asp-controller="Usuario" asp-route-id="@Model.Id" asp-action="Apagar">Sim</a>
    <a class="btn btn-danger" role="button" asp-controller="Usuario" asp-action="Index">Não</a>
</div>

Views/Usuario/Editar.cshtml
@using AgendaOnline.Data.Enums;
@model Usuario

@{
    ViewData["Title"] = "Editar Usuario";
}

<div class="text-center">
    <h1 class="display-4">Editar usuário</h1>
</div>

<form asp-controller="Usuario" asp-action="Editar" method="post">
    
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Nome do usuário">
        @Html.ValidationMessageFor(x=>x.Nome)
    </div>
    <br />

    <div class="form-group">
        <label for="email" class="form-label">E-mail</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="E-mail do usuário">
        @Html.ValidationMessageFor(x=>x.Email)
    </div>
    <br />

    <div class="form-group">
        <label for="telefone" class="form-label">Login</label>
        <input type="text" asp-for="Login" class="form-control" placeholder="Login do usuário">
        @Html.ValidationMessageFor(x=>x.Login)
    </div>
    <br />

    <div class="form-group">
        <label for="telefone" class="form-label">Perfil</label>
        <select asp-for="Perfil" class="form-control">
            <option value="">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.Padrao">Padrao</option>
        </select>
        @Html.ValidationMessageFor(x=>x.Perfil)
    </div>
    <br />

    <button type="submit" class="btn btn-primary">Editar</button>
    <a class="btn btn-secondary" asp-controller="Usuario" asp-action="Index" role="button">Voltar</a>
</form>

Views/Usuario/Index.cshtml
@model List<Usuario>
@{
    ViewData["Title"] = "Listagem de Usuarios";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Usuario" asp-action="Criar">Novo Usuario</a>
    </div>
    <br />

    @if (TempData["MsgSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MsgSucesso"]
        </div>
    }

    @if (TempData["MsgErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MsgErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Listagem de Usuarios</h1>

    <table class="table" id="tbnUsuarios">
        <thead>
            <tr>
                <th scope="col" hidden="hidden">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Login</th>
                <th scope="col">E-mail</th>
                <th scope="col">Perfil</th>
                <th scope="col"> Total de contatos</th>
                <th scope="col">Data de cadastro</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var usuario in Model)
                {
                    <tr>
                        <th scope="row" hidden="hidden">@usuario.Id</th>
                        <td>@usuario.Nome</td>
                        <td>@usuario.Login</td>
                        <td>@usuario.Email</td>
                        <td>@(usuario.Perfil == AgendaOnline.Data.Enums.PerfilEnum.Admin ? "Administrador" : "Padrão")</td>

                        <td>
                            <a href="javascript:" usuario-id="@usuario.Id" class="btn btn-success btn-sm btn-total-contatos">
                                @(usuario.Contatos != null && usuario.Contatos.Any() ? usuario.Contatos.Count() : 0)
                            </a>
                        </td>

                        <td>@usuario.DataCadastro</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-outline-danger" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="DeletarConfirmacao">Excluir</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum usuario encontrado!</td></tr>
            }
        </tbody>
    </table>

    <div id="modalContatosUsuario" class="modal" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Contatos</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div id="listaContatosUsuario">

                    </div>

                </div>
            </div>
        </div>
    </div>

</div>

Views/Usuario/_ContatosUsuario.cshtml
@model List<Contato>

<table id="tbnContatosUsuario" class="display" style="width: 100%">
    <thead>
        <tr>
            <th scope="col" hidden="hidden">#</th>
            <th scope="col">Nome</th>
            <th scope="col">E-mail</th>
            <th scope="col">Telefone</th>
        </tr>
    </thead>
    <tbody>

        @if (Model != null && Model.Any())
        {
            foreach (var contato in Model)
            {
                <tr>
                    <th scope="row">@contato.Id</th>
                    <th>@contato.Nome</th>
                    <th>@contato.Email</th>
                    <th>@contato.Telefone</th>
                </tr>
            }
        }
        else
        {
            <tr class="odd">
                <td valign="top" colspan="4">Nenhum contato encontrado!</td>
            </tr>
        }

    </tbody>
</table>